#pragma warning disable 1591
namespace ANFIS.ILNumerics_deploy {
    /// <summary>
    /// This type supports ILNumerics infrastructure. Do not edit the code!
    /// </summary>
    /// <remarks>This type is automatically generated by ILNumerics Ultimate VS. If you encounter problems compiling this file, make sure to reference ILNumerics.Core in your project!</remarks>
    [System.ComponentModel.LicenseProvider(typeof(ILNumerics.Licensing.ILLicenseProvider))]  // <- ILNumerics.Core is needed here!
    public class IlLicHelper32Ab13C5124142C8A69Ff06Ac721Aa7E {
        /// <summary>
        /// Licensing Helper (internal use)
        /// </summary>
        public IlLicHelper32Ab13C5124142C8A69Ff06Ac721Aa7E() { System.ComponentModel.LicenseManager.Validate(typeof(IlLicHelper32Ab13C5124142C8A69Ff06Ac721Aa7E), this); } }
}